scripts: fix menuconfig due to DSOlink change
Due to stricter link rules[1], make menuconfig fails. This patch
fixes it. This is the error:

$ make menuconfig
  HOSTLD  scripts/kconfig/mconf
/usr/bin/ld: scripts/kconfig/lxdialog/checklist.o: undefined reference to symbol 'acs_map'
/usr/bin/ld: note: 'acs_map' is defined in DSO /lib/libtinfo.so.5 so try adding it to the linker command line
/lib/libtinfo.so.5: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[1]: *** [scripts/kconfig/mconf] Error 1
make: *** [menuconfig] Error 2

[1]. http://fedoraproject.org/wiki/UnderstandingDSOLinkChange

Signed-off-by: Ricardo Neri <ricardo.neri@ti.com>